spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mywork?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      username: ENC(mzJnp09OZekJFLJfTr1IhQ==)
      password: ENC(PUZlrSO2Cl9I6vk+MVGObg==)
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    time-zone: GMT+8
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
